### ISSUE TITLE
why pack_padded?

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [pcyin/pytorch_nmt#1]
https://github.com/pcyin/pytorch_nmt/blob/0055235be2546f53946795f5a2a6bc1b3b0877b2/nmt.py#L560

Why do u saving the lengths of the src sentences if they are all the same length? 
Why are u using pack_padded_sequence? 
As far as I understand data_iter returns batches where src sentences all have the same lengths. Because all pairs come from "buckets" witch stores src_sentences with the same lengths, am I right?
Thank you.

**Comment by pcyin** [comment]
Nice catch! Sorry this is redundant. I did this in case I want to implement batch encoding with source sentences of different lengths.
