### ISSUE TITLE
dataset preprocessing

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [pcyin/pytorch_nmt#2]
Can you please tell which preprocessing did you use? I found that original IWSLT consist of some xml files. Thank you!

**Comment by pcyin** [comment]
Hi! For the training set, I replaced all singletons with `<unk>`. For dev/test sets they are the same as the official release :)

**Comment by pum-purum-pum-pum** [comment]
Thank you, again.
And you just somehow concatenated all these xml files for dev/test.
I'm looking at this one:
https://wit3.fbk.eu/mt.php?release=2014-01

**Comment by pcyin** [comment]
I used the data preprocessing scripts at `https://github.com/harvardnlp/BSO/tree/master/data_prep`. Hope this helps!

**Comment by pum-purum-pum-pum** [comment]
I tried it and it just works :) Thank you so much!
