### ISSUE TITLE
你好，想问一下这套系统支持迁移学习吗？

### ISSUE THREAD

**Issue by PengboLiu** [pcyin/pytorch_nmt#3]
看博主是中国人 直接用汉语提问了  见谅
我想用zh-en的out-domain大语料训练，再用zh-en特定语料训练得到domain adaptation的NMT模型
您这套系统支持这种训练吗
多谢了

**Comment by pcyin** [comment]
你好，理论上可以的，可以先用大语料作为训练数据pre-train数个epoch，然后载入训练好的模型，用特定语料作为训练数据继续训练。

现在的代码暂不支持载入pre-train model继续训练，但这个功能非常容易实现，可以参考`test()`里如何载入一个train好的模型，把那段代码移植到`train()`函数里就好。

**Comment by PengboLiu** [comment]
多谢了！
